spring:
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always

  metrics:
    tags:
      application: ${spring.application.name}
  info:
    env:
      enabled: true

logging:
  level:
    com.parut.gateway: debug
